# Generated by Django 5.2 on 2025-06-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_license', models.CharField(help_text='License number of the pharmacy', max_length=50)),
                ('alert_type', models.CharField(choices=[('license_expiry', 'License Expiring'), ('missing_documents', 'Missing Documents'), ('inspection_due', 'Inspection Due'), ('compliance_violation', 'Compliance Violation')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Alert',
                'verbose_name_plural': 'Compliance Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoHOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('licensing', 'Pharmacy Licensing'), ('inspection', 'Pharmacy Inspection'), ('compliance', 'Regulatory Compliance'), ('administration', 'Administration')], max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MoH Officer',
                'verbose_name_plural': 'MoH Officers',
            },
        ),
        migrations.CreateModel(
            name='MoHPharmacyRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('pharmacist_name', models.CharField(max_length=100)),
                ('pharmacist_license', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('oromia', 'Oromia'), ('amhara', 'Amhara'), ('tigray', 'Tigray'), ('snnp', 'Southern Nations, Nationalities, and Peoples'), ('afar', 'Afar'), ('somali', 'Somali'), ('benishangul', 'Benishangul-Gumuz'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('dire_dawa', 'Dire Dawa')], default='addis_ababa', max_length=20)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('woreda', models.CharField(default='Not Specified', max_length=100)),
                ('kebele', models.CharField(default='Not Specified', max_length=100)),
                ('address_detail', models.TextField(default='Address not specified')),
                ('license_type', models.CharField(choices=[('retail', 'Retail Pharmacy'), ('hospital', 'Hospital Pharmacy'), ('wholesale', 'Wholesale Pharmacy'), ('manufacturing', 'Manufacturing Pharmacy')], default='retail', max_length=20)),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('pending', 'Pending Review'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('moh_officer', models.CharField(help_text='MoH officer who registered this pharmacy', max_length=100)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True)),
                ('compliance_score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('business_license_verified', models.BooleanField(default=False)),
                ('pharmacist_certificate_verified', models.BooleanField(default=False)),
                ('pharmacy_permit_verified', models.BooleanField(default=False)),
                ('business_license_document', models.FileField(blank=True, null=True, upload_to='moh_documents/business_licenses/')),
                ('pharmacist_certificate_document', models.FileField(blank=True, null=True, upload_to='moh_documents/pharmacist_certificates/')),
                ('pharmacy_permit_document', models.FileField(blank=True, null=True, upload_to='moh_documents/pharmacy_permits/')),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='moh_documents/inspection_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MoH Pharmacy Record',
                'verbose_name_plural': 'MoH Pharmacy Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_license', models.CharField(help_text='License number of the requesting pharmacy', max_length=50)),
                ('request_type', models.CharField(choices=[('initial', 'Initial License'), ('renewal', 'License Renewal'), ('modification', 'License Modification'), ('reinstatement', 'License Reinstatement')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_inspection', 'Requires Inspection')], default='pending', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moh_verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
