# Generated by Django 5.2 on 2025-06-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0001_initial'),
    ]

    operations = [
    ]
