# Generated by Django 5.2 on 2025-06-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0001_initial'),
        ('pharmacy', '0007_pharmacy_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mohpharmacyregistry',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moh_record', to='pharmacy.pharmacy'),
        ),
        migrations.AlterModelTable(
            name='mohpharmacyregistry',
            table='moh_mohpharmacyrecord',
        ),
    ]
