# Generated by Django 5.2 on 2025-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Delivery Person'), ('picked_up', 'Picked up from Pharmacy'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
