# Generated by Django 5.2 on 2025-06-09 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_options_alter_prescription_options_and_more'),
        ('pharmacy', '0006_mohpharmacyrecord_business_license_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('security', 'Security Concern'), ('data', 'Data Integrity'), ('performance', 'Performance Issue'), ('user_report', 'User Report'), ('pharmacy_report', 'Pharmacy Report'), ('verification', 'Verification Issue'), ('moh_sync', 'MoH Synchronization'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='open', max_length=15)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url_path', models.CharField(blank=True, max_length=500, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='incident_reports/screenshots/')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='incident_reports/logs/')),
                ('additional_file', models.FileField(blank=True, null=True, upload_to='incident_reports/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('related_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('login_attempt', 'Failed Login Attempts'), ('data_breach', 'Potential Data Breach'), ('unauthorized_access', 'Unauthorized Access'), ('suspicious_activity', 'Suspicious Activity'), ('malware', 'Malware Detection'), ('ddos', 'DDoS Attack'), ('injection', 'SQL/Code Injection Attempt'), ('xss', 'Cross-Site Scripting'), ('csrf', 'CSRF Attack'), ('file_upload', 'Malicious File Upload'), ('other', 'Other Security Concern')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=10)),
                ('description', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('target_url', models.CharField(blank=True, max_length=500, null=True)),
                ('detection_method', models.CharField(blank=True, max_length=100, null=True)),
                ('detection_rules', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('response_action', models.CharField(blank=True, max_length=200, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_alerts', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('incident', 'New Incident Report'), ('security', 'Security Alert'), ('system', 'System Issue'), ('pharmacy', 'Pharmacy Registration'), ('verification', 'Verification Request'), ('maintenance', 'Maintenance Required'), ('update', 'System Update'), ('backup', 'Backup Status')], max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.incidentreport')),
                ('related_security_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.securityalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
