# Generated by Django 5.2 on 2025-06-12 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_options_alter_prescription_options_and_more'),
        ('pharmacy', '0007_pharmacy_license_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_verification_requests', to='pharmacy.pharmacy'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_verification_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
