# Generated by Django 5.2 on 2025-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_order_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_prescriptions/'),
        ),
    ]
