# Generated by Django 5.2 on 2025-06-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_prescription_image'),
        ('pharmacy', '0007_pharmacy_license_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('receipt_data', models.JSONField(help_text='Complete receipt data including all items and totals')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_by_customer', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_by_pharmacy', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='customer.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='customer.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='customer.payment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pharmacy.pharmacy')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['customer', '-generated_at'], name='customer_re_custome_569ca8_idx'), models.Index(fields=['pharmacy', '-generated_at'], name='customer_re_pharmac_b7594f_idx'), models.Index(fields=['receipt_number'], name='customer_re_receipt_6955d8_idx')],
            },
        ),
    ]
