# Generated by Django 5.2 on 2025-07-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_add_scheduled_order_fields'),
        ('customer', '0014_auto_20250711_1437'),
    ]

    operations = [
    ]
