# Generated by Django 5.2 on 2025-07-15 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_add_cartitem_validation_data'),
        ('pharmacy', '0008_pharmacy_is_24_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityalert',
            name='investigated_by',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_security_alert',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='requested_by',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='customer_re_custome_569ca8_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='customer_re_pharmac_b7594f_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='customer_re_receipt_6955d8_idx',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_incident',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ocr_validation_data',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='additional_file',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='log_file',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='related_pharmacy',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='related_user',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='reporter_email',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='reporter_phone',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='resolution_date',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='stack_trace',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='url_path',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_data',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('pharmacy_registration', 'Pharmacy Registration'), ('incident_report', 'Incident Report'), ('payment_issue', 'Payment Issue'), ('system_alert', 'System Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default='No address provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When this order should be processed', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_message',
            field=models.TextField(blank=True, help_text='Customer message for scheduled order', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('paid', 'Paid'), ('completed', 'Completed'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.payment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='print_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SecurityAlert',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
