# Generated by Django 5.2 on 2025-07-21 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_remove_securityalert_investigated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pharmacy_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pharmacy_review_required',
            field=models.BooleanField(default=False, help_text='True if OCR confidence is below 100%'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pharmacy_review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved by Pharmacy'), ('rejected', 'Rejected by Pharmacy'), ('not_required', 'Review Not Required')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
