# Generated by Django 5.2 on 2025-07-21 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_cartitem_pharmacy_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(blank=True, help_text='Reference to original cart item for OCR data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.cartitem'),
        ),
    ]
