# Generated by Django 5.2 on 2025-05-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=True, help_text='Check if this medicine requires a prescription'),
        ),
    ]
