# Generated by Django 5.2 on 2025-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_prescription_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_documents/'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist_certificate',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_documents/'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_documents/'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
