# Generated by Django 5.2 on 2025-06-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacy_business_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='moh_verification_data',
            field=models.JSONField(blank=True, help_text='Ministry of Health verification results', null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='moh_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'MoH Verified'), ('failed', 'MoH Verification Failed'), ('manual_review', 'Requires Manual Review')], default='pending', max_length=20),
        ),
    ]
