# Generated by Django 5.2 on 2025-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_pharmacy_moh_verification_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoHPharmacyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('pharmacist_name', models.CharField(max_length=100)),
                ('pharmacist_license', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('oromia', 'Oromia'), ('amhara', 'Amhara'), ('tigray', 'Tigray'), ('snnp', 'Southern Nations, Nationalities, and Peoples'), ('afar', 'Afar'), ('somali', 'Somali'), ('benishangul', 'Benishangul-Gumuz'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('dire_dawa', 'Dire Dawa')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('address_detail', models.TextField()),
                ('license_type', models.CharField(choices=[('retail', 'Retail Pharmacy'), ('hospital', 'Hospital Pharmacy'), ('wholesale', 'Wholesale Pharmacy'), ('manufacturing', 'Manufacturing Pharmacy')], default='retail', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('moh_officer', models.CharField(help_text='MoH officer who registered this pharmacy', max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ministry of Health Pharmacy Record',
                'verbose_name_plural': 'Ministry of Health Pharmacy Records',
                'ordering': ['-registration_date'],
            },
        ),
    ]
