# Generated by Django 5.2 on 2025-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_mohpharmacyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mohpharmacyrecord',
            name='business_license_document',
            field=models.FileField(blank=True, help_text='Business license document', null=True, upload_to='moh_documents/business_licenses/'),
        ),
        migrations.AddField(
            model_name='mohpharmacyrecord',
            name='inspection_report_document',
            field=models.FileField(blank=True, help_text='Latest inspection report', null=True, upload_to='moh_documents/inspection_reports/'),
        ),
        migrations.AddField(
            model_name='mohpharmacyrecord',
            name='pharmacist_certificate_document',
            field=models.FileField(blank=True, help_text='Pharmacist certificate document', null=True, upload_to='moh_documents/pharmacist_certificates/'),
        ),
        migrations.AddField(
            model_name='mohpharmacyrecord',
            name='pharmacy_permit_document',
            field=models.FileField(blank=True, help_text='Pharmacy operating permit', null=True, upload_to='moh_documents/pharmacy_permits/'),
        ),
    ]
