# Generated by Django 5.2 on 2025-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_mohpharmacyrecord_business_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='license_type',
            field=models.CharField(choices=[('retail', 'Retail Pharmacy'), ('hospital', 'Hospital Pharmacy'), ('wholesale', 'Wholesale Pharmacy'), ('manufacturing', 'Manufacturing Pharmacy')], default='retail', max_length=20),
        ),
    ]
