# Generated by Django 5.2 on 2025-07-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_pharmacy_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_24_hour',
            field=models.BooleanField(default=False, help_text='Check if pharmacy operates 24/7'),
        ),
    ]
