# Generated by Django 5.2 on 2025-07-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacy_is_24_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Not required for 24-hour pharmacies', null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Not required for 24-hour pharmacies', null=True),
        ),
    ]
