# Generated by Django 5.2.4 on 2025-07-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_pharmacy_closing_time_and_more'),
    ]

    operations = [
    ]
